version: '3.7'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootybooty
      MYSQL_DATABASE: wolkesieben_local
    ports:
      - 3307:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  pubsub:
    image: google/cloud-sdk:emulators
    ports:
      - 8085:8085
    entrypoint: /bin/bash -c "gcloud config set project vet-shelter && /google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=0.0.0.0 --port=8085"
