version: '3.7'

services:
  recommender:
    image: recommender-cloud-function
    build:
      context: .
    environment:
      CHAT_API_URL: https://chat-api-xm7n7eaepa-ey.a.run.app/ # http://host.docker.internal:3000 # service on your host machine
      APP_SERVICE_URL: https://app-api-xm7n7eaepa-ey.a.run.app/ # http://host.docker.internal:8000
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080
    depends_on:
      - pubsub
    command: npm run watch

  pubsub:
    image: google/cloud-sdk:emulators
    ports:
      - 8085:8085
    entrypoint: /bin/bash -c "gcloud config set project vet-shelter && /google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=0.0.0.0 --port=8085"
