version: '3.7'

services:
  recommender:
    image: recommender-cloud-function
    build:
      context: .
    environment:
      CHAT_API_URL: http://host.docker.internal:3000 # service on your host machine
      DATABASE_HOST: db
      DATABASE_PORT: 3306 # use container port due to local bridge
      DATABASE_USER: root
      DATABASE_PASSWORD: rootybooty
      DATABASE_NAME: wolkesieben_local
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080
    depends_on:
      - db
      - pubsub
    command: npm run watch

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootybooty
      MYSQL_DATABASE: wolkesieben_local
    ports:
      - 3307:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  pubsub:
    image: google/cloud-sdk:emulators
    ports:
      - 8085:8085
    entrypoint: /bin/bash -c "gcloud config set project vet-shelter && /google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=0.0.0.0 --port=8085"
